apiVersion: v2
name: reference-quarkus-mvn-workflow
description: |
  A Helm chart for Kubernetes to deploy the Ploigos Workflow (Typical) for the
  "reference-quarkus-mvn" application.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
- name: ploigos-workflow-tekton-pipeline-typical
  versions: "0.19.0-edge.1"
  repository: "https://ploigos.github.io/ploigos-charts"
